config/routes.rb
Rails.application.routes.draw do
  
  root 'home_page_items#show'

  resources :home_page_items,  only: [:edit, :update, :show]
  resources :about_page_items, except: [:index]
  resources :audios, except: [:show]
  resources :generous_supporters, except: [:show]
  resources :benefactors, except: [:show]
  resources :events

  get '/about_us',                   to: 'about_page_items#index'
  get '/manage_events',              to: 'events#manage_events'
  get '/manage_song_files',          to: 'audios#manage_song_files'
  get '/manage_generous_supporters', to: 'generous_supporters#manage_generous_supporters'
  get '/manage_benefactors',         to: 'benefactors#manage_benefactors'
  get '/support_us',                 to: 'benefactors#index'
  get '/contact_us',                 to: 'contacts#contact'
  get '/hear_us_sing',               to: 'events#index'
end

app/models/about_page_item.rb
class AboutPageItem < ApplicationRecord
  validates_presence_of :name, :bio, :role
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio.rb
class Audio < ApplicationRecord
  belongs_to :event

  validates_presence_of :title
end

app/models/benefactor.rb
class Benefactor < ApplicationRecord
  validates_presence_of :name, :image_caption
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :title, :start_date, :end_date, :ticket_url

  has_many :audios
end

app/models/generous_supporter.rb
class GenerousSupporter < ApplicationRecord
end

app/models/home_page_item.rb
class HomePageItem < ApplicationRecord
  validates_presence_of :summary
end

app/controllers/about_page_items_controller.rb
class AboutPageItemsController < ApplicationController
  layout "about"

  def new
    @about_page_item = AboutPageItem.new
  end

  def create
    @about_page_item = AboutPageItem.new(about_page_item_params)

    if @about_page_item.save
      redirect_to about_us_path
    else
      render :new
    end
  end

  def index
    @about_page_items = AboutPageItem.all
  end

  def edit
    @about_page_item = AboutPageItem.find(params[:id])
  end

  def update
    @about_page_item = AboutPageItem.find(params[:id])

    if @about_page_item.update(about_page_item_params)
      redirect_to about_us_path
    else
      render :edit
    end
  end

  def destroy
    @about_page_item = AboutPageItem.find(params[:id]).destroy

    redirect_to about_us_path
  end

  private

    def about_page_item_params
      params.require(:about_page_item).permit(:name, :role, :bio)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  def new
    @audio_file = Audio.new
    @events = Event.all
  end

  def create
    @audio_file = Audio.new(audio_params)

    if @audio_file.save
      redirect_to manage_song_files_path
    else
      render :new
    end
  end

  def index
    @audio_files = Audio.all
  end

  def edit
    @audio_file = Audio.find(params[:id])
    @events = Event.all
  end

  def update
    @audio_file = Audio.find(params[:id])

    if @audio_file.update(audio_params)
      redirect_to manage_song_files_path
    else
      render :edit
    end
  end

  def destroy
    @audio_file = Audio.find(params[:id]).destroy
    redirect_to manage_song_files_path
  end

  def manage_song_files
    @audio_files = Audio.all
  end

  private

    def audio_params
      params.require(:audio).permit(:title, :event_id)
    end
end

app/controllers/benefactors_controller.rb
class BenefactorsController < ApplicationController
  layout 'support_us'
  
  def new
    @benefactor = Benefactor.new
  end

  def create
    @benefactor = Benefactor.create(benefactor_params)

    if @benefactor.save
      redirect_to manage_benefactors_path
    else
      render :new
    end
  end

  def edit
    @benefactor = Benefactor.find(params[:id])
  end

  def update
    @benefactor = Benefactor.find(params[:id])

    if @benefactor.update(benefactor_params)
      redirect_to manage_benefactors_path
    else
      render :edit
    end
  end

  def index
    @benefactors = Benefactor.all
  end

  def manage_benefactors
    @benefactors = Benefactor.all
  end

  def destroy
    @benefactors = Benefactor.find(params[:id]).destroy
    redirect_to manage_benefactors_path
  end

  private

    def benefactor_params
      params.require(:benefactor).permit(:name, :image_caption)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def contact
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout 'hear_us_sing'
  
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to manage_events_path
    else
      render :new
    end
  end

  def index
    @events = Event.all
  end

  def manage_events
    @events = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to manage_events_path
    else
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id]).destroy

    redirect_to manage_events_path
  end

  private

    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :ticket_url, :you_tube_url)
    end
end

app/controllers/generous_supporters_controller.rb
class GenerousSupportersController < ApplicationController
  layout "generous_supporters"
  
  def new
    @generous_supporter = GenerousSupporter.new
  end

  def create
    @generous_supporter = GenerousSupporter.create(generous_supporter_params)

    if @generous_supporter.save
      redirect_to manage_generous_supporters_path
    else
      render :new
    end
  end

  def index
    @generous_supporters = GenerousSupporter.all
  end

  def manage_generous_supporters
    @generous_supporters = GenerousSupporter.all
  end

  def edit
    @generous_supporter = GenerousSupporter.find(params[:id])
  end

  def update
    @generous_supporter = GenerousSupporter.find(params[:id])

    if @generous_supporter.update(generous_supporter_params)
      redirect_to manage_generous_supporters_path
    else
      render :edit
    end
  end

  def destroy
    @generous_supporter = GenerousSupporter.find(params[:id]).destroy
    redirect_to manage_generous_supporters_path
  end

  private

    def generous_supporter_params
      params.require(:generous_supporter).permit(:name, :website_url, :category)
    end
end

app/controllers/home_page_items_controller.rb
class HomePageItemsController < ApplicationController
  layout "home"
  
  def show
    @home_page_item = HomePageItem.first
  end

  def edit
    @home_page_item = HomePageItem.find(params[:id])
  end

  def update
    @home_page_item = HomePageItem.find(params[:id])

    if @home_page_item.update(home_page_item_params)
      redirect_to root_url
    else
      render :edit 
    end
  end

  private
    def home_page_item_params
      params.require(:home_page_item).permit(:summary)
    end
end

app/helpers/about_page_items_helper.rb
module AboutPageItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/benefactors_helper.rb
module BenefactorsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/generous_supporters_helper.rb
module GenerousSupportersHelper
end

app/helpers/home_page_items_helper.rb
module HomePageItemsHelper
end

app/views/about_page_items/_form.html.erb
<h1>Fill Out The Form</h1>

<%= form_with model: @about_page_item, local: true do |form| %>
  <% if @about_page_item.errors.any? %>
    <% @about_page_item.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :role %>
  <%= form.text_field :role %>

  <%= form.label :bio %>
  <%= form.text_area :bio %>

  <%= form.submit %>
<% end %>

app/views/about_page_items/edit.html.erb
<h1>Edit This Fool</h1>

<%= render 'form' %>

app/views/about_page_items/index.html.erb
<div class="row mt-80">
  <% @about_page_items.each do |about_page_item| %>
    <div class="col-md-4"> 
      <div class="card" style="width: 18rem;">
        <div class="card-header">
          <strong><%= about_page_item.name %></strong>
        </div>
    
        <div class="card-body">
          <%= image_tag("paul_smith", class: 'card-img-top') %>
          <p><em><%= about_page_item.role %></em></p>
          <p class="card-text">
            <%= about_page_item.bio %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>


<!-- create a manage_about_page view/controller/route -->

app/views/about_page_items/new.html.erb
<h1>Create a new dude</h1>

<%= render 'form' %>

app/views/audios/_form.html.erb
<% if @events.blank? %>
  <p>Please create an <%= link_to "Event", new_event_path %> before uploading files.</p>
<% else %>
  <%= form_with model: @audio_file, local: true do |form| %>
    <% if @audio_file.errors.any? %>
      <% @audio_file.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    <% end %>

    <%= form.label :event_id, 'Event' %>
    <%= form.collection_select :event_id, Event.all, :id, :title %>

    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.submit %>
  <% end %>
<% end %>

app/views/audios/edit.html.erb
<h1>Edit song file</h1>

<%= render 'form' %>

app/views/audios/index.html.erb
<h1>All songs</h1>

<% @audio_files.each do |audio_file| %>
  <p>
    <%= audio_file.title %>
  </p>
<% end %>

app/views/audios/manage_song_files.html.erb
<h1>Manage Song Files</h1>

<% @audio_files.each do |audio_file| %>
  <p>
    <%= audio_file.title %>
    <%= audio_file.event.title %>
    <%= link_to "Edit", edit_audio_path(audio_file) %>
    <%= link_to "Delete", audio_file, method: :delete, 
                                      data: { confirm: "You sure?" } %>
  </p>
<% end %>

app/views/audios/new.html.erb
<h1>Create new audio file</h1>

<%= render 'form' %>

app/views/benefactors/_form.html.erb
<%= form_with model: @benefactor, local: true do |form| %>
  <% if @benefactor.errors.any? %>
    <% @benefactor.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :image_caption %>
  <%= form.text_area :image_caption %>

  <%= form.submit %>
<% end %>

app/views/benefactors/edit.html.erb
<h1>Edit Benefactor</h1>

<%= render 'form' %>

app/views/benefactors/index.html.erb
<main role="main">
  <h1 class="mt-40">Support Us</h1>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @benefactors.each_with_index do |benefactor, index| %>
        <li data-target='#MyCarousel' data-slide-to="#{index}" class="#{'active' if index == 0}"></li>
      <% end %>
    </ol>

    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "2014-grant-check" %> <!-- change this to @benefactors.first.image_url -->
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Benefactor Name Goes Here</h1>
            <p><%= @benefactors.first.image_caption %></p>
          </div>
        </div>
      </div>

      <% @benefactors.drop(1).each do |benefactor| %>
      <div class="carousel-item">
        <%= image_tag "phs-donation-2" %><!-- change this to benefactor.image_url -->
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Benefactor Name Goes Here</h1>
            <p><%= benefactor.image_caption %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <p>
    Ticket sales account for only a small part of the Parker Chorale's expenses, so we count on donations from organizations and individuals to meet our annual budget. The generosity of our patrons allows us to reserve weekly rehearsal space, purchase music, hire the best instrumentalists & conductors, and support music education in our community through our Parker Chorale Grant Program that provides funding for Douglas County School District High School Vocal Music Programs.
  </p>

  <p>
    The Parker Chorale is a 501c3 (non-profit) organization incorporated in the State of Colorado so all contributions are 100% tax-deductible. Patrons can make a general contribution, sponsor a concert, place an ad in our programs and/or be a part of our Generous Supporters page on this website.
  </p>

  <p>
    For more information on supporting the Parker Chorale and music education in Douglas County, please email us.
  </p>

  <p>Click here to make a donation:</p>

  <p><%= image_tag "donation_image" %></p>

  <p>or Checks may be sent to:</p>
  <p>Parker Chorale</p>
  <p>17051 Numa Pl. Parker, CO 80134</p>
</main>

app/views/benefactors/manage_benefactors.html.erb
<h1>Manage Benefactors</h1>

<% @benefactors.each do |benefactor| %>
  <p>
    <%= benefactor.name %>
    <%= link_to "Edit", edit_benefactor_path(benefactor) %>
    <%= link_to "Delete", benefactor, method: :delete, 
                                      data: { confirm: "You sure?" } %>
  </p>
<% end %>

app/views/benefactors/new.html.erb
<h1>Create New Benefactor</h1>

<%= render 'form' %>

app/views/events/_form.html.erb
<%= form_with model: @event, local: true do |form| %>
  <% if @event.errors.any? %>
    <% @event.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :start_date %>
  <%= form.datetime_field :start_date %>

  <%= form.label :end_date %>
  <%= form.datetime_field :end_date %>

  <%= form.label :ticket_url %>
  <%= form.text_field :ticket_url %>

  <%= form.label :you_tube_url %>
  <%= form.text_field :you_tube_url %>

  <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Update Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1 class="mt-80 text-center">Hear Us Sing</h1>
<p class="text-center">Catch us at one of our upcoming performances, or check out videos of some of our past performances.</p>

<% @events.each do |event| %>
  <div class="row mt-80">
    <div class="col-md-6">
      <div class="card w-75" style="width: 18rem;">
        <div class="card-header">
          <strong><%= event.title %></strong><em><%= event.start_date %> - <%= event.end_date %></em>
        </div>
        <div class="card-body">
          <%= image_tag("Classic-Parker-Holiday_2016", class: 'card-img-top') %>
          <p class="card-text">
            <a class="btn btn-block btn-primary mt-10" href="#" role="button">Buy Tickets! &raquo;</a>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <iframe width="500" height="290" src="https://www.youtube.com/embed/mSkISrG2474" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
  </div>
<% end %>

app/views/events/manage_events.html.erb
<h1>Manage Events</h1>

<%= link_to "Create New Event", new_event_path %>

<% @events.each do |event| %>
  <p>
    <%= event.title %>
    <%= link_to "Update Info", edit_event_path(event) %>
    <%= link_to "Delete Event", event, method: :delete, 
                                       data: { confirm: "You sure?" } %>
  </p>
<% end %>

app/views/events/new.html.erb
<h1>Create a new event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h1>Event Info</h1>

<%= @event.title %>
<%= @event.start_date %>
<%= @event.end_date %>
<%= @event.ticket_url %>
<%= @event.you_tube_url %>

app/views/generous_supporters/_form.html.erb
<%= form_with model: @generous_supporter, local: true do |form| %>
  <% if @generous_supporter.errors.any? %>
    <% @generous_supporter.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :website_url %>
  <%= form.text_field :website_url %>

  <%= form.label :category %>
  <%= form.select :category, ['business', 'individual'] %>

  <%= form.submit %>
<% end %>

app/views/generous_supporters/edit.html.erb
<h1>Edit Supporter</h1>

<%= render 'form' %>

app/views/generous_supporters/index.html.erb
<h1>Our Generous Supporters</h1>
<p>Parker Chorale would like to extend thanks to the following generous Supporters.</p>
<p>Contact Us to learn how to contribute.</p>

<div class="row mt-40">
  <div class="col-md-6">
    <% @generous_supporters.each do |supporter| %>
    <div class="card mt-40">
      <h5 class="card-header"><%= supporter.name %></h5>
      <div class="card-body">
        <a href="<%= supporter.website_url %>" class="card-title"><%= image_tag "comp-tutor", class: 'card-img-top' %></a>
        <p class="card-text">555-555-5555</p> <!-- add phone column to table -->
      </div>
    </div>
    <% end %>
  </div>

  <div class="col-md-4 offset-md-2">
    <!-- Individuals go here -->
    <div class="card mt-40" style="width: 18rem;">
      <div class="card-header">
        Thank You To the Following Individuals
      </div>
      <ul class="list-group list-group-flush">
        <% @generous_supporters.each do |supporter| %>
          <li class="list-group-item"><%= supporter.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/generous_supporters/manage_generous_supporters.html.erb
<h1>Manage Generous Supporters</h1>

<% @generous_supporters.each do |generous_supporter| %>
  <p>
    <%= generous_supporter.name %>
    <%= link_to "Edit", edit_generous_supporter_path(generous_supporter) %>
    <%= link_to "Delete", generous_supporter_path(generous_supporter), 
                          method: :delete,
                          data: { confirm: "You sure?" } %>
  </p>
<% end %>

app/views/generous_supporters/new.html.erb
<h1>Create new supporter</h1>

<%= render 'form' %>

app/views/home_page_items/_form.html.erb
<h1>Fill out the form</h1>

<%= form_with model: @home_page_item, local: true do |form| %>

  <% if @home_page_item.errors.any? %>
    <% @home_page_item.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <%= form.label :summary %>
  <%= form.text_area :summary %>

  <%= form.submit %>
<% end %>

app/views/home_page_items/edit.html.erb
<h1>Edit Home Page</h1>

<%= render 'form' %>

app/views/home_page_items/show.html.erb
<main role="main">

  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("homepage_background", class: "first-slide") %>
    </div>
  </div>

  <div class="container mt-40">
    <div class="row">
      <div class="col-md-12">
        <h1 class="">Parker Chorale - <em>Sharing The Gift of Song</em></h1>
        <p>
          <%= @home_page_item.summary %>
        </p>
      </div>
    </div>
  </div>

  <div class="container marketing mt-40">
    <div class="row">
      <div class="col-lg-4">
        <%= image_tag("chorale_logo",  width: '200', height: '80') %>
        <p class="mt-40"><a class="btn btn-block btn-primary" href="#" role="button">Buy Tickets! &raquo;</a></p>
      </div>
      <div class="col-lg-4">
        <%= image_tag("youtube_logo",  width: '240', height: '80') %>
        <p class="mt-40"><a class="btn btn-block btn-primary" href="https://www.youtube.com/channel/UCULrEMrY4fjYDY-JyPiIf2w" role="button" target="_blank">Subscribe &raquo;</a></p>
      </div>
      <div class="col-lg-4">
        <%= image_tag("facebook_logo",  width: '80', height: '80') %>
        <p class="mt-40"><a class="btn btn-block btn-primary" href="https://www.facebook.com/parkerchorale/" role="button", target="_blank">Like and Follow Us &raquo;</a></p>
      </div>
    </div>
  </div>

</main>

<%= link_to "Edit - Put me on the manage page", edit_home_page_item_path(@home_page_item) %>