config/routes.rb
Rails.application.routes.draw do
  
  root 'home_page_items#show'

  resources :home_page_items,  only: [:edit, :update, :show]
  resources :about_page_items, except: [:index]
  resources :audios, except: [:show]
  resources :generous_supporters, except: [:show]
  resources :benefactors, except: [:show]
  resources :events

  get '/about_us',                   to: 'about_page_items#index'
  get '/manage_events',              to: 'events#manage_events'
  get '/manage_song_files',          to: 'audios#manage_song_files'
  get '/manage_generous_supporters', to: 'generous_supporters#manage_generous_supporters'
  get '/manage_benefactors',         to: 'benefactors#manage_benefactors'
  get '/support_us',                 to: 'benefactors#index'
  get '/contact_us',                 to: 'contacts#contact'
  get '/hear_us_sing',               to: 'events#index'
end

app/models/about_page_item.rb
class AboutPageItem < ApplicationRecord
  validates_presence_of :name, :bio, :role
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio.rb
class Audio < ApplicationRecord
  belongs_to :event

  validates_presence_of :title
end

app/models/benefactor.rb
class Benefactor < ApplicationRecord
  validates_presence_of :name, :image_caption
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :title, :start_date, :end_date, :ticket_url

  has_many :audios
end

app/models/generous_supporter.rb
class GenerousSupporter < ApplicationRecord
end

app/models/home_page_item.rb
class HomePageItem < ApplicationRecord
  validates_presence_of :summary
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  def new
    @audio_file = Audio.new
    @events = Event.all
  end

  def create
    @audio_file = Audio.new(audio_params)

    if @audio_file.save
      redirect_to manage_song_files_path
    else
      render :new
    end
  end

  def index
    @audio_files = Audio.all
  end

  def edit
    @audio_file = Audio.find(params[:id])
    @events = Event.all
  end

  def update
    @audio_file = Audio.find(params[:id])

    if @audio_file.update(audio_params)
      redirect_to manage_song_files_path
    else
      render :edit
    end
  end

  def destroy
    @audio_file = Audio.find(params[:id]).destroy
    redirect_to manage_song_files_path
  end

  def manage_song_files
    @audio_files = Audio.all
  end

  private

    def audio_params
      params.require(:audio).permit(:title, :event_id)
    end
end

app/controllers/benefactors_controller.rb
class BenefactorsController < ApplicationController
  layout 'support_us'
  
  def new
    @benefactor = Benefactor.new
  end

  def create
    @benefactor = Benefactor.create(benefactor_params)

    if @benefactor.save
      redirect_to manage_benefactors_path
    else
      render :new
    end
  end

  def edit
    @benefactor = Benefactor.find(params[:id])
  end

  def update
    @benefactor = Benefactor.find(params[:id])

    if @benefactor.update(benefactor_params)
      redirect_to manage_benefactors_path
    else
      render :edit
    end
  end

  def index
    @benefactors = Benefactor.all
  end

  def manage_benefactors
    @benefactors = Benefactor.all
  end

  def destroy
    @benefactors = Benefactor.find(params[:id]).destroy
    redirect_to manage_benefactors_path
  end

  private

    def benefactor_params
      params.require(:benefactor).permit(:name, :image_caption)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def contact
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout 'hear_us_sing'
  
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to manage_events_path
    else
      render :new
    end
  end

  def index
    @events = Event.all
  end

  def manage_events
    @events = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to manage_events_path
    else
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id]).destroy

    redirect_to manage_events_path
  end

  private

    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :ticket_url, :you_tube_url)
    end
end

app/helpers/about_page_items_helper.rb
module AboutPageItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/benefactors_helper.rb
module BenefactorsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/generous_supporters_helper.rb
module GenerousSupportersHelper
end

app/helpers/home_page_items_helper.rb
module HomePageItemsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Parker Chorale</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to root_path, class: 'nav-link' do %>
          Home<span class="sr-only">(current)</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_us_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Hear Us Sing", hear_us_sing_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Support Us", support_us_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Our Generous Supporters", generous_supporters_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_us_path, class: 'nav-link' %>
      </li>
    </ul>
    
  </div>
</nav>

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ParkerChorale | About</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'about_page_items', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ParkerChorale</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/layouts/generous_supporters.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ParkerChorale | Generous Supporters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'generous_supporters', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/hear_us_sing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ParkerChorale | Hear Us Sing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'events', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ParkerChorale</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'home_page_items', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/layouts/support_us.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ParkerChorale | Support Us</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'benefactors', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>